### ISSUE TITLE
Can't compile on Ubuntu 24.10 - Missing vaapi.h

### ISSUE THREAD

**Issue by YetAnotherRandomGuy** [bluecherrydvr/bluecherry-client#346]
Compiling from source as per https://github.com/bluecherrydvr/bluecherry-client/blob/master/README.txt , with all dependencies noted there installed... I can't find any package in Ubuntu 24 that includes the "vaapi.h" file referenced in source... and thus, make fails. (`./configure` didn't seem to mind anything, it succeeded)

This seems to have been last included in Jammy (22.04): 
https://packages.ubuntu.com/search?suite=jammy&arch=any&mode=exactfilename&searchon=contents&keywords=vaapi.h

There are some similarly named files, e.g. "hwcontext_vaapi.h" (in [libavutil-dev] package) ... would an alias to this maybe work? 

Should it not be clear from the above, the make whine looks like this: 
`src/core/VaapiHWAccel.cpp:14:10: fatal error: libavcodec/vaapi.h: No such file or directory`
`   14 | #include <libavcodec/vaapi.h>`
`      |          ^~~~~~~~~~~~~~~~~~~~`
`compilation terminated.`
`make: *** [Makefile:2145: src/core/bluecherry_client-VaapiHWAccel.o] Error 1`

Happy to provide any other info, or try any alternatives. 

TIA!
